### ISSUE TITLE
アイコンが全部 Twitter へのリンク

### ISSUE THREAD

**Issue by Raclamusi** [Luke256/Luke256.dev#1]
ヘッダに Twitter 、GitHub 、Zenn のアイコンがありますが、すべて Twitter へのリンクになっています。

https://github.com/Luke256/Luke256.dev/blob/7f3a3d9ddb1607687eba0c469379a9deff618a2c/src/components/layer/index.tsx#L26-L40

**Comment by Luke256** [comment]
本当だ！
ご報告ありがとうございます！
